import CoreGraphics

/// **Generated by the Artwork tuning window — its "Write to source" button.**
/// Edit it there and press the button; anything typed here by hand is lost the
/// next time it writes.
///
/// The numbers live apart from `ArtworkTuning` so there is exactly one source
/// of truth for them. That file declares each knob and documents why it exists;
/// this one is only what the knobs are currently set to, which is the part that
/// changes in an afternoon and belongs in a diff.
enum ArtworkDefaults {
    static let darkMidSplit: CGFloat = 0.20
    static let midLightSplit: CGFloat = 0.90
    static let flatMidSplit: CGFloat = 0.20
    static let midBusySplit: CGFloat = 0.90

    static let exposureOnLight = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.60,
        .init(tone: .dark, busy: .mid): 0.60,
        .init(tone: .dark, busy: .busy): 0.80,
        .init(tone: .mid, busy: .flat): 0.80,
        .init(tone: .mid, busy: .mid): 0.60,
        .init(tone: .mid, busy: .busy): 0.80,
        .init(tone: .light, busy: .flat): -0.50,
        .init(tone: .light, busy: .mid): 0.80,
        .init(tone: .light, busy: .busy): 0.80,
    ])
    static let exposureOnDark = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.40,
        .init(tone: .dark, busy: .mid): -0.60,
        .init(tone: .dark, busy: .busy): -0.30,
        .init(tone: .mid, busy: .flat): -0.30,
        .init(tone: .mid, busy: .mid): -0.60,
        .init(tone: .mid, busy: .busy): -0.30,
        .init(tone: .light, busy: .flat): -1.00,
        .init(tone: .light, busy: .mid): -0.30,
        .init(tone: .light, busy: .busy): -0.30,
    ])
    static let punchOnLight = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 1.75,
        .init(tone: .dark, busy: .mid): 5.00,
        .init(tone: .dark, busy: .busy): 2.50,
        .init(tone: .mid, busy: .flat): 2.50,
        .init(tone: .mid, busy: .mid): 5.00,
        .init(tone: .mid, busy: .busy): 2.50,
        .init(tone: .light, busy: .flat): 2.50,
        .init(tone: .light, busy: .mid): 2.50,
        .init(tone: .light, busy: .busy): 2.50,
    ])
    static let punchOnDark = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 1.75,
        .init(tone: .dark, busy: .mid): 5.00,
        .init(tone: .dark, busy: .busy): 2.50,
        .init(tone: .mid, busy: .flat): 2.50,
        .init(tone: .mid, busy: .mid): 5.00,
        .init(tone: .mid, busy: .busy): 2.50,
        .init(tone: .light, busy: .flat): 2.50,
        .init(tone: .light, busy: .mid): 2.50,
        .init(tone: .light, busy: .busy): 2.50,
    ])

    static let saturationOnLight = ArtworkPalette.SaturationCeiling(atDark: 0.80, atBright: 0.60)
    static let saturationOnDark = ArtworkPalette.SaturationCeiling(atDark: 0.80, atBright: 0.60)
    static let vibranceOnLight = ArtworkPalette.Vibrance(atDark: 0.25, atBright: 0.20)
    static let vibranceOnDark = ArtworkPalette.Vibrance(atDark: 0.25, atBright: 0.20)

    static let tintOpacityOnLight = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.12,
        .init(tone: .dark, busy: .mid): 0.12,
        .init(tone: .dark, busy: .busy): 0.12,
        .init(tone: .mid, busy: .flat): 0.12,
        .init(tone: .mid, busy: .mid): 0.12,
        .init(tone: .mid, busy: .busy): 0.12,
        .init(tone: .light, busy: .flat): 0.12,
        .init(tone: .light, busy: .mid): 0.12,
        .init(tone: .light, busy: .busy): 0.12,
    ])
    static let tintOpacityOnDark = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.12,
        .init(tone: .dark, busy: .mid): 0.12,
        .init(tone: .dark, busy: .busy): 0.24,
        .init(tone: .mid, busy: .flat): 0.24,
        .init(tone: .mid, busy: .mid): 0.12,
        .init(tone: .mid, busy: .busy): 0.24,
        .init(tone: .light, busy: .flat): 0.24,
        .init(tone: .light, busy: .mid): 0.24,
        .init(tone: .light, busy: .busy): 0.24,
    ])
    static let watermarkOpacityOnLight = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.40,
        .init(tone: .dark, busy: .mid): 0.04,
        .init(tone: .dark, busy: .busy): 0.04,
        .init(tone: .mid, busy: .flat): 0.04,
        .init(tone: .mid, busy: .mid): 0.04,
        .init(tone: .mid, busy: .busy): 0.04,
        .init(tone: .light, busy: .flat): 0.20,
        .init(tone: .light, busy: .mid): 0.04,
        .init(tone: .light, busy: .busy): 0.04,
    ])
    static let watermarkOpacityOnDark = ArtworkPalette.ToneMap(values: [
        .init(tone: .dark, busy: .flat): 0.40,
        .init(tone: .dark, busy: .mid): 0.04,
        .init(tone: .dark, busy: .busy): 0.04,
        .init(tone: .mid, busy: .flat): 0.04,
        .init(tone: .mid, busy: .mid): 0.04,
        .init(tone: .mid, busy: .busy): 0.04,
        .init(tone: .light, busy: .flat): 0.20,
        .init(tone: .light, busy: .mid): 0.04,
        .init(tone: .light, busy: .busy): 0.04,
    ])
}
